Algoritmo "idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/04/2024
Var
idade:real


Inicio
escreva("digite sua idade:")
leia(idade)
se idade >=18 entao
escreva("você é maior de idade:")
senao
escreva("você é menor de idade:")
fimse


Fimalgoritmo